FROM golang AS build_base

#RUN apk add --no-cache git
WORKDIR /tmp/app

COPY . .

RUN go build -o ./out/app .

FROM scratch

COPY --from=build_base /tmp/app/out/app src/app

# This container exposes port 8080 to the outside world
EXPOSE 8080

# Run the binary program produced by `go install`
CMD ["src/app"]
